# Generated by Django 6.0.2 on 2026-02-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ("-created_at",), "verbose_name_plural": "Companies"},
        ),
    ]
