# Generated by Django 5.1.7 on 2025-03-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ("-created_at",), "verbose_name_plural": "Companies"},
        ),
    ]
