# Generated by Django 5.1.7 on 2025-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram_chat_id_user_telegram_sync_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin'), ('manager', 'Manager'), ('sales', 'Sales')], default='guest', max_length=20),
        ),
    ]
