# Generated by Django 5.1.7 on 2025-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="deal_notes/"),
        ),
    ]
