# Generated by Django 6.0.2 on 2026-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="deal_notes/"),
        ),
    ]
