# Generated by Django 6.0.2 on 2026-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_note_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
