# Generated by Django 5.1.7 on 2025-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_note_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
