# Generated by Django 6.0.2 on 2026-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
