# Generated by Django 5.1.7 on 2025-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
