# Generated by Django 5.1.7 on 2025-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="original_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
