# Generated by Django 6.0.2 on 2026-03-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="original_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
