# Generated by Django 5.1.7 on 2025-04-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_note_original_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminded_1h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminded_5m',
            field=models.BooleanField(default=False),
        ),
    ]
