# Generated by Django 6.0.2 on 2026-03-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_note_original_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminded_1h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminded_5m',
            field=models.BooleanField(default=False),
        ),
    ]
