# Generated by Django 6.0.2 on 2026-03-02 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_company_options'),
        ('sales', '0008_reminder_reminded_1h_reminder_reminded_5m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(condition=models.Q(('is_done', False), ('reminded_1h', False)), fields=['date'], name='idx_active_reminders_1h'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(condition=models.Q(('is_done', False), ('reminded_5m', False)), fields=['date'], name='idx_active_reminders_5m'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['owner', 'is_done'], name='sales_remin_owner_i_b6a140_idx'),
        ),
    ]
