# Generated by Django 5.1.7 on 2025-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_activitylog_deleted_activitylog_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='trigger',
            field=models.BooleanField(default=False),
        ),
    ]
